### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by RehanPlayz** [hwdotexe/iControlU#2]
Seems like a pretty cool plugin but it would be nice if it is updated to the latest versions

**Comment by RehanPlayz** [comment]
@hwdotexe

**Comment by Greenlio** [comment]
As it says in the readme, the main contributor will likely not be updating due to not doing plugin development anymore.

**Comment by MCGOOnYouTube** [comment]
Hi! This thread isn't active, but @RehanPlayz, I would be happy to update it for you. Just contact me on Discord - MarkusMCGO#8870.

**Comment by RehanPlayz** [comment]
> Hi! This thread isn't active, but @RehanPlayz, I would be happy to update it for you. Just contact me on Discord - MarkusMCGO#8870.

I sent you a friend request (My username is "AlphaKitten#6525")

**Comment by hwdotexe** [comment]
This repository welcomes Pull Requests from anyone who wishes to contribute. Otherwise, you may Fork and distribute your own versions as specified in `LICENSE`.

Closing this issue
